name: dart_mui
description: A starting point for Dart libraries or applications.
version: 0.1.0
homepage: https://github.com/Atom735/dart-mui

environment:
  sdk: '>=2.9.3 <3.0.0'

dependencies:
  js: ^0.6.0
  react: ^5.6.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.15.0
  build_runner: ^1.9.0
  build_test: ^1.2.0
  build_web_compilers: ^2.11.0
